FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY job.html /usr/share/nginx/html/job.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY config.js /usr/share/nginx/html/config.js
COPY app.js /usr/share/nginx/html/app.js
COPY job.js /usr/share/nginx/html/job.js
