from pathlib import Path

from app.core.config import get_settings


class AssemblyService:
    def __init__(self) -> None:
        self.settings = get_settings()

    def build_ffmpeg_script(self, working_dir: Path, scene_count: int) -> Path:
        script_path = working_dir / "assemble.sh"
        lines = [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f"# Generated for {scene_count} scenes",
            "# Replace placeholders with real mp4/wav assets after model integration.",
            f"{self.settings.ffmpeg_binary} -f concat -safe 0 -i scene_manifest.txt -i narration_mix.wav "
            "-c:v libx264 -c:a aac final_video.mp4",
        ]
        script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return script_path

    def build_preview_html(self, working_dir: Path, job_id: str, prompt: str) -> Path:
        preview_path = working_dir / "preview.html"
        preview_path.write_text(
            f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{job_id}</title></head>
<body style="font-family: Arial, sans-serif; background:#10151c; color:#f4f7fb; padding:32px;">
<h1>Job {job_id}</h1>
<p>{prompt}</p>
<p>This preview file is generated by the backend scaffold. Replace placeholder files with rendered media as local GPU models come online.</p>
</body></html>
""",
            encoding="utf-8",
        )
        return preview_path
